HECHOS = [
    # Hechos de ingredientes por receta
    ("incluye", "chilaquiles_verdes", "tortilla_de_maiz"),
    ("incluye", "chilaquiles_verdes", "cebolla"),
    ("incluye", "chilaquiles_verdes", "tomates_verdes"),
    ("incluye", "chilaquiles_verdes", "chile_serrano"),
    ("incluye", "chilaquiles_verdes", "chiles_jalapenos"),
    ("incluye", "chilaquiles_verdes", "cebolla_blanca"),
    ("incluye", "arroz_con_pollo", "pollo"),
    ("incluye", "arroz_con_pollo", "arroz"),
    ("incluye", "arroz_con_pollo", "cebolla"),
    ("incluye", "arroz_con_pollo", "pimiento"),
    ("incluye", "arroz_con_pollo", "tomate"),
    ("incluye", "tacos_carne_asada", "carne_res"),
    ("incluye", "tacos_carne_asada", "tortilla_de_maiz"),
    ("incluye", "tacos_carne_asada", "cebolla"),
    ("incluye", "tacos_carne_asada", "cilantro"),
    ("incluye", "ceviche", "pescado_blanco"),
    ("incluye", "ceviche", "cebolla_roja"),
    ("incluye", "ceviche", "cilantro"),
    ("incluye", "ceviche", "aji"),
    ("incluye", "tamales", "cerdo"),
    ("incluye", "tamales", "harina_maiz"),
    ("incluye", "tamales", "chile"),
    ("incluye", "carne_de_res_salteada", "carne_res"),
    ("incluye", "carne_de_res_salteada", "arroz"),
    ("incluye", "carne_de_res_salteada", "papas"),
    ("incluye", "carne_de_res_salteada", "cebolla"),
    ("incluye", "carne_de_res_salteada", "tomate"),
    ("incluye", "carne_de_res_salteada", "aji_amarillo"),
    ("incluye", "enchiladas_rojas", "pollo"),
    ("incluye", "enchiladas_rojas", "tortilla_de_maiz"),
    ("incluye", "enchiladas_rojas", "cebolla"),
    ("incluye", "tacos_al_pastor", "cerdo"),
    ("incluye", "tacos_al_pastor", "tortilla_de_maiz"),
    ("incluye", "tacos_al_pastor", "cebolla"),
    ("incluye", "tacos_al_pastor", "cilantro"),
    ("incluye", "tacos_al_pastor", "piña"),
    ("incluye", "quesadillas_flor_calabaza", "tortilla_de_maiz"),
    ("incluye", "quesadillas_flor_calabaza", "flor_calabaza"),
    ("incluye", "enchiladas_vegetarianas", "tortillas_de_maiz"),
    ("incluye", "enchiladas_vegetarianas", "tomates_rojos"),
    ("incluye", "enchiladas_vegetarianas", "cebolla"),
    ("incluye", "enchiladas_vegetarianas", "chiles_poblanos"),
    ("incluye", "enchiladas_vegetarianas", "zanahorias"),
    ("incluye", "enchiladas_vegetarianas", "calabacitas"),
    ("incluye", "enchiladas_vegetarianas", "elote"),
    ("incluye", "tacos_de_champiñones", "tortillas_de_maiz"),
    ("incluye", "tacos_de_champiñones", "champiñones"),
    ("incluye", "tacos_de_champiñones", "cebolla"),
    ("incluye", "tacos_de_champiñones", "chiles_serranos"),
    ("incluye", "tacos_de_champiñones", "limones"),
    ("incluye", "tacos_de_lentejas", "lentejas"),
    ("incluye", "tacos_de_lentejas", "tortillas_de_maiz"),
    ("incluye", "tacos_de_lentejas", "cebolla"),
    ("incluye", "tacos_de_lentejas", "tomates"),
    ("incluye", "tacos_de_lentejas", "lechuga"),
    ("incluye", "pimiento_relleno", "arroz_cocido"),
    ("incluye", "pimiento_relleno", "pimientos_morrones"),
    ("incluye", "pimiento_relleno", "cebolla"),
    ("incluye", "pimiento_relleno", "jitomate"),
    ("incluye", "pimiento_relleno", "elote"),
    ("incluye", "sopa_de_tortilla", "tortillas_de_maiz"),
    ("incluye", "sopa_de_tortilla", "tomates_rojos"),
    ("incluye", "sopa_de_tortilla", "cebolla"),
    ("incluye", "sopa_de_tortilla", "aguacate"),
    ("incluye", "molinetes_mexicanos", "tortillas_de_harina"),
    ("incluye", "molinetes_mexicanos", "chiles_poblanos"),
    ("incluye", "molinetes_mexicanos", "cebolla"),
    ("incluye", "ceviche_de_mango", "tostadas"),
    ("incluye", "ceviche_de_mango", "mango"),
    ("incluye", "ceviche_de_mango", "pepino"),
    ("incluye", "ceviche_de_mango", "cebolla_morada"),
    ("incluye", "ceviche_de_mango", "chiles_serranos"),
    ("incluye", "ceviche_de_mango", "limones"),
    ("incluye", "picadillo_de_soya_mexicano", "soya_texturizada"),
    ("incluye", "picadillo_de_soya_mexicano", "cebolla"),
    ("incluye", "picadillo_de_soya_mexicano", "tomates"),
    ("incluye", "picadillo_de_soya_mexicano", "papa"),
    ("incluye", "picadillo_de_soya_mexicano", "zanahoria"),
    ("incluye", "tortitas_de_papa_rellena", "papas"),
    ("incluye", "tortitas_de_papa_rellena", "pan_molido"),
    ("incluye", "tortitas_de_papa_rellena", "cebolla"),
    ("incluye", "tortitas_de_papa_rellena", "jitomate"),
    ("incluye", "tortitas_de_papa_rellena", "elote"),
    ("incluye", "calabacitas_al_horno", "calabacitas"),
    ("incluye", "calabacitas_al_horno", "cebolla"),
    ("incluye", "calabacitas_al_horno", "jitomate"),
    ("incluye", "calabacitas_al_horno", "elote"),
    ("incluye", "coctel_de_camaron", "camaron"),
    ("incluye", "coctel_de_camaron", "cilantro"),
    ("incluye", "coctel_de_camaron", "cebolla_morada"),
    ("incluye", "coctel_de_camaron", "chile_serrano"),
    ("incluye", "coctel_de_camaron", "tomates_verdes"),
    ("incluye", "coctel_de_camaron", "aguacate"),
    ("incluye", "ensalada_de_quinoa", "quinoa"),
    ("incluye", "ensalada_de_quinoa", "quinoa"),
    ("incluye", "ensalada_de_quinoa", "pepino"),
    ("incluye", "ensalada_de_quinoa", "jitomate"),
    ("incluye", "ensalada_de_quinoa", "cebolla"),
    ("incluye", "ensalada_de_quinoa", "pimiento_rojo"),
    ("incluye", "curry_de_garbanzos", "garbanzos"),
    ("incluye", "curry_de_garbanzos", "arroz_integral"),
    ("incluye", "curry_de_garbanzos", "tomate"),
    ("incluye", "curry_de_garbanzos", "cebolla"),
    ("incluye", "curry_de_garbanzos", "ajo"),
    ("incluye", "hamburguesas_de_frijol_negro", "frijoles_negros"),
    ("incluye", "hamburguesas_de_frijol_negro", "pan_integral"),
    ("incluye", "hamburguesas_de_frijol_negro", "avena"),
    ("incluye", "hamburguesas_de_frijol_negro", "cebolla"),
    ("incluye", "hamburguesas_de_frijol_negro", "jitomate"),
    ("incluye", "hamburguesas_de_frijol_negro", "lechuga"),
    ("incluye", "hamburguesas_de_frijol_negro", "aguacate"),
    ("incluye", "spaghetti_con_pure_de_berenjena", "tofu"),
    ("incluye", "spaghetti_con_pure_de_berenjena", "spaghetti_integral"),
    ("incluye", "spaghetti_con_pure_de_berenjena", "berenjena"),
    ("incluye", "spaghetti_con_pure_de_berenjena", "ajo"),
    ("incluye", "enchiladas_de_queso", "queso_fresco"),
    ("incluye", "enchiladas_de_queso", "tortillas_de_maiz"),
    ("incluye", "enchiladas_de_queso", "tomate"),
    ("incluye", "enchiladas_de_queso", "chile"),
    ("incluye", "enchiladas_de_queso", "ajo"),
    ("incluye", "enchiladas_de_queso", "cebolla"),
    ("incluye", "enchiladas_de_queso", "lechuga"),
    ("incluye", "omelette_de_espinaca_y_champiñones", "huevo"),
    ("incluye", "omelette_de_espinaca_y_champiñones", "pan_integral"),
    ("incluye", "omelette_de_espinaca_y_champiñones", "espinaca"),
    ("incluye", "omelette_de_espinaca_y_champiñones", "champiñones"),
    ("incluye", "lasagna_de_vegetales", "queso_mozzarella"),
    ("incluye", "lasagna_de_vegetales", "ricotta"),
    ("incluye", "lasagna_de_vegetales", "pasta_para_lasagna"),
    ("incluye", "lasagna_de_vegetales", "calabacita"),
    ("incluye", "lasagna_de_vegetales", "berenjena"),
    ("incluye", "lasagna_de_vegetales", "zanahoria"),
    ("incluye", "lasagna_de_vegetales", "espinaca"),
    ("incluye", "lasagna_de_vegetales", "tomate"),
    ("incluye", "sopa_de_brocoli_y_queso", "queso_cheddar"),
    ("incluye", "sopa_de_brocoli_y_queso", "pan_integral"),
    ("incluye", "sopa_de_brocoli_y_queso", "brocoli"),
    ("incluye", "mole poblano", "pollo"),
    ("incluye", "mole poblano", "tortillas_de_maiz"),
    ("incluye", "mole poblano", "bolillo"),
    ("incluye", "mole poblano", "cebolla"),
    ("incluye", "mole poblano", "jitomate"),
    ("incluye", "mole poblano", "platano_macho"),
    ("incluye", "mole poblano", "cacahuates"),
    ("incluye", "mole poblano", "pasas"),
    ("incluye", "mole poblano", "chiles_mulatos"),
    ("incluye", "mole poblano", "chiles_pasillas"),
    ("incluye", "mole poblano", "chiles_chipotle"),
    ("incluye", "mole poblano", "ajo"),
    ("incluye", "pozole", "carne_de_cerdo"),
    ("incluye", "pozole", "maiz_pozolero"),
    ("incluye", "pozole", "tostadas"),
    ("incluye", "pozole", "cebolla"),
    ("incluye", "pozole", "cebolla_picada"),
    ("incluye", "pozole", "lechuga"),
    ("incluye", "pozole", "rábanos"),
    ("incluye", "pozole", "limones"),
    ("incluye", "pozole", "chiles_guajillo"),
    ("incluye", "pozole", "ajos"),
    ("incluye", "chiles en nogada", "carne_molida_de_cerdo"),
    ("incluye", "chiles en nogada", "cebolla"),
    ("incluye", "chiles en nogada", "chiles_poblanos"),
    ("incluye", "chiles en nogada", "duraznos"),
    ("incluye", "chiles en nogada", "pera"),
    ("incluye", "chiles en nogada", "manzana"),
    ("incluye", "chiles en nogada", "granada"),
    ("incluye", "chiles en nogada", "pasas"),
    ("incluye", "cochinita pibil", "carne_de_cerdo"),
    ("incluye", "cochinita pibil", "cebolla_morada"),
    ("incluye", "cochinita pibil", "chiles_habaneros"),
    ("incluye", "birria", "carne_de_chivo_o_res"),
    ("incluye", "birria", "cebolla"),
    ("incluye", "birria", "cebolla_picada"),
    ("incluye", "birria", "tomates"),
    ("incluye", "birria", "limones"),
    ("incluye", "birria", "chiles_guajillo"),
    ("incluye", "birria", "chiles_ancho"),
    ("incluye", "huevos rancheros", "huevos"),
    ("incluye", "huevos rancheros", "tortillas_de_maiz"),
    ("incluye", "huevos rancheros", "tomates_rojos"),
    ("incluye", "huevos rancheros", "cebolla"),
    ("incluye", "huevos rancheros", "chiles_serranos"),
    ("incluye", "caldo de res", "carne_de_res_con_hueso"),
    ("incluye", "caldo de res", "zanahorias"),
    ("incluye", "caldo de res", "papas"),
    ("incluye", "caldo de res", "calabazas"),
    ("incluye", "caldo de res", "elote"),
    ("incluye", "caldo de res", "repollo"),
    ("incluye", "caldo de res", "cebolla"),
    ("incluye", "caldo de res", "limones"),
    ("incluye", "chicharrón en salsa verde", "chicharrón"),
    ("incluye", "chicharrón en salsa verde", "tomates_verdes"),
    ("incluye", "chicharrón en salsa verde", "cebolla"),
    ("incluye", "chicharrón en salsa verde", "chiles_serranos"),
    ("incluye", "tacos de pescado", "filete_de_pescado_blanco"),
    ("incluye", "tacos de pescado", "tortillas_de_maiz"),
    ("incluye", "tacos de pescado", "harina_de_trigo"),
    ("incluye", "tacos de pescado", "repollo"),
    ("incluye", "tacos de pescado", "limones"),
    ("incluye", "albóndigas en chipotle", "carne_molida_de_res"),
    ("incluye", "albóndigas en chipotle", "huevo"),
    ("incluye", "albóndigas en chipotle", "pan_molido"),
    ("incluye", "albóndigas en chipotle", "cebolla"),
    ("incluye", "albóndigas en chipotle", "tomates_rojos"),
    ("incluye", "tostadas_de_tinga", "pollo_desmenuzado"),
    ("incluye", "tostadas_de_tinga", "tostadas"),
    ("incluye", "tostadas_de_tinga", "jitomates"),
    ("incluye", "tostadas_de_tinga", "cebolla"),
    ("incluye", "tostadas_de_tinga", "ajo"),
    ("incluye", "tostadas_de_tinga", "lechuga"),
    ("incluye", "tostadas_de_tinga", "chile_chipotle"),
    ("incluye", "flautas_de_pollo", "pollo_desmenuzado"),
    ("incluye", "flautas_de_pollo", "tortillas_de_maíz"),
    ("incluye", "flautas_de_pollo", "lechuga"),
    ("incluye", "flautas_de_pollo", "jitomate"),
    ("incluye", "fajitas_de_pollo", "pollo"),
    ("incluye", "fajitas_de_pollo", "tortillas_de_maíz"),
    ("incluye", "fajitas_de_pollo", "pimiento_rojo"),
    ("incluye", "fajitas_de_pollo", "pimiento_verde"),
    ("incluye", "fajitas_de_pollo", "cebolla"),
    ("incluye", "sopes_mexicanos", "carne_deshebrada"),
    ("incluye", "sopes_mexicanos", "masa_de_maíz"),
    ("incluye", "sopes_mexicanos", "lechuga"),
    ("incluye", "sopes_mexicanos", "jitomate"),
    ("incluye", "enchiladas_verdes", "pollo_desmenuzado"),
    ("incluye", "enchiladas_verdes", "tortillas_de_maíz"),
    ("incluye", "enchiladas_verdes", "tomates_verdes"),
    ("incluye", "enchiladas_verdes", "chile_jalapeño"),
    ("incluye", "enchiladas_verdes", "cebolla"),
    ("incluye", "enchiladas_verdes", "cilantro"),
    ("incluye", "pechuga_empanizada", "pechugas_de_pollo"),
    ("incluye", "pechuga_empanizada", "harina"),
    ("incluye", "pechuga_empanizada", "pan_molido"),
    ("incluye", "pechuga_empanizada", "lechuga"),
    ("incluye", "pechuga_empanizada", "jitomate"),
    ("incluye", "chiles_rellenos", "carne_molida (picadillo)"),
    ("incluye", "chiles_rellenos", "harina"),
    ("incluye", "chiles_rellenos", "chiles_poblanos"),
    ("incluye", "chiles_rellenos", "jitomate"),
    ("incluye", "chiles_rellenos", "ajo"),
    ("incluye", "chiles_rellenos", "cebolla"),
    ("incluye", "milanesa_de_res_con_ensalada", "milanesas_de_res"),
    ("incluye", "milanesa_de_res_con_ensalada", "pan_molido"),
    ("incluye", "milanesa_de_res_con_ensalada", "lechuga"),
    ("incluye", "milanesa_de_res_con_ensalada", "jitomate"),
    ("incluye", "milanesa_de_res_con_ensalada", "pepino"),
    ("incluye", "pollo_con_brocoli_y_zanahoria", "pechuga_de_pollo"),
    ("incluye", "pollo_con_brocoli_y_zanahoria", "brócoli"),
    ("incluye", "pollo_con_brocoli_y_zanahoria", "zanahoria"),
    ("incluye", "pollo_con_brocoli_y_zanahoria", "cebolla"),
    ("incluye", "tortitas_de_atun_en_salsa", "atun_en_lata"),
    ("incluye", "tortitas_de_atun_en_salsa", "huevo"),
    ("incluye", "tortitas_de_atun_en_salsa", "pan_molido"),
    ("incluye", "tortitas_de_atun_en_salsa", "jitomates"),
    ("incluye", "tortitas_de_atun_en_salsa", "cebolla"),
    ("incluye", "tortitas_de_atun_en_salsa", "ajo"),
    ("incluye", "tortitas_de_atun_en_salsa", "chile_serrano"),
    ("incluye", "tortitas_de_atun_en_salsa", "perejil"),
    # Tiempos de preparación en minutos
    ("tiempo_preparacion", "chilaquiles_verdes", 40),
    ("tiempo_preparacion", "arroz_con_pollo", 50),
    ("tiempo_preparacion", "tacos_carne_asada", 30),
    ("tiempo_preparacion", "ceviche", 20),
    ("tiempo_preparacion", "tamales", 90),
    ("tiempo_preparacion", "carne_de_res_salteada", 30),
    ("tiempo_preparacion", "enchiladas_rojas", 45),
    ("tiempo_preparacion", "tacos_al_pastor", 60),
    ("tiempo_preparacion", "quesadillas_flor_calabaza", 30),
    ("tiempo_preparacion", "enchiladas_vegetarianas", 45),
    ("tiempo_preparacion", "tacos_de_champiñones", 25),
    ("tiempo_preparacion", "tacos_de_lentejas", 40),
    ("tiempo_preparacion", "pimiento_relleno", 50),
    ("tiempo_preparacion", "sopa_de_tortilla", 35),
    ("tiempo_preparacion", "molinetes_mexicanos", 30),
    ("tiempo_preparacion", "ceviche_de_mango", 20),
    ("tiempo_preparacion", "picadillo_de_soya_mexicano", 25),
    ("tiempo_preparacion", "tortitas_de_papa_rellena", 50),
    ("tiempo_preparacion", "calabacitas_al_horno", 40),
    ("tiempo_preparacion", "coctel_de_camaron", 40),
    ("tiempo_preparacion", "ensalada_de_quinoa", 25),
    ("tiempo_preparacion", "curry_de_garbanzos", 40),
    ("tiempo_preparacion", "hamburguesas_de_frijol_negro", 50),
    ("tiempo_preparacion", "spaghetti_con_pure_de_berenjena", 35),
    ("tiempo_preparacion", "enchiladas_de_queso", 45),
    ("tiempo_preparacion", "omelette_de_espinaca_y_champiñones", 25),
    ("tiempo_preparacion", "lasagna_de_vegetales", 60),
    ("tiempo_preparacion", "sopa_de_brocoli_y_queso", 30),
    ("tiempo_preparacion", "mole poblano", 180),
    ("tiempo_preparacion", "pozole", 120),
    ("tiempo_preparacion", "chiles en nogada", 150),
    ("tiempo_preparacion", "cochinita pibil", 240),
    ("tiempo_preparacion", "birria", 300),
    ("tiempo_preparacion", "huevos rancheros", 30),
    ("tiempo_preparacion", "caldo de res", 120),
    ("tiempo_preparacion", "chicharrón en salsa verde", 45),
    ("tiempo_preparacion", "tacos de pescado", 40),
    ("tiempo_preparacion", "albóndigas en chipotle", 60),
    ("tiempo_preparacion", "tostadas_de_tinga", 35),
    ("tiempo_preparacion", "flautas_de_pollo", 40),
    ("tiempo_preparacion", "fajitas_de_pollo", 30),
    ("tiempo_preparacion", "sopes_mexicanos", 40),
    ("tiempo_preparacion", "enchiladas_verdes", 50),
    ("tiempo_preparacion", "pechuga_empanizada", 30),
    ("tiempo_preparacion", "chiles_rellenos", 60),
    ("tiempo_preparacion", "milanesa_de_res_con_ensalada", 40),
    ("tiempo_preparacion", "pollo_con_brocoli_y_zanahoria", 35),
    ("tiempo_preparacion", "tortitas_de_atun_en_salsa", 40),
    # Chiles poco picantes
    ("chile_poco", "chile_jalapeno"),
    ("chile_poco", "chile_poblano"),
    ("chile_poco", "aji_amarillo"),
    # Chiles picantes
    ("chile_picante", "chile_serrano"),
    ("chile_picante", "chile_guajillo"),
    ("chile_picante", "chile_ancho"),
    ("chile_picante", "chile_mulato"),
]

